name: Update TryHackMe Badge

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: '0 8 * * *'

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v4

      - name: Generate/Update TryHackMe badge
        uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: 'OMAR404'
          committer_username: 'github-actions[bot]'
          committer_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'update: refresh TryHackMe badge'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
