name: TryHackMe Badge Update

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add TryHackMe Badge
        run: |
          README_FILE="README.md"
          BADGE='<img src="https://tryhackme-badges.s3.amazonaws.com/BRAIN404.png" alt="Your Image Badge" />'

          if grep -q "<!-- tryhackme-badge -->" "$README_FILE"; then
            sed -i "s|<!-- tryhackme-badge -->|$BADGE|g" "$README_FILE"
          else
            echo -e "\n$BADGE" >> "$README_FILE"
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$README_FILE"
          git commit -m "update: add TryHackMe badge" || echo "No changes to commit"
          git push
