name: Update TryHackMe Badge

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests

      - name: Generate TryHackMe Badge
        run: |
          python3 - <<'EOF'
          import requests
          import re

          README_FILE = "README.md"
          USER_ID = "5662904"  # Remplace par ton userPublicId
          PROFILE_URL = "https://tryhackme.com/p/BRAIN404"

          url = f"https://tryhackme.com/api/v2/badges/public-profile?userPublicId={USER_ID}"
          headers = {"User-Agent": "Mozilla/5.0"}
          resp = requests.get(url, headers=headers)

          if resp.status_code != 200:
              raise Exception(f"Erreur API TryHackMe: {resp.status_code}")

          data = resp.json()

          username = data['data']['user']['username']
          level = data['data']['user']['level']
          points = data['data']['user']['points']
          avatar = data['data']['user']['avatar']

          # Générer le badge Markdown cliquable
          badge_md = f"[![{username} - Level {level} - {points} pts]({avatar})]({PROFILE_URL})"

          # Lire README
          with open(README_FILE, "r") as f:
              content = f.read()

          # Remplacer le commentaire
          if "<!-- tryhackme-badge -->" in content:
              content = re.sub(r"<!-- tryhackme-badge -->", badge_md, content)
          else:
              content += f"\n{badge_md}\n"

          # Écrire README
          with open(README_FILE, "w") as f:
              f.write(content)
          EOF

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update TryHackMe badge" || echo "No changes to commit"
          git push
