name: Update TryHackMe Badge

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests

      - name: Generate TryHackMe Badge
        run: |
          README_FILE="README.md"
          USER_ID="5662904"
          PROFILE_URL="https://tryhackme.com/p/BRAIN404"

          # Récupérer le JSON
          DATA=$(curl -s -H "User-Agent: Mozilla/5.0" "https://tryhackme.com/api/v2/badges/public-profile?userPublicId=${USER_ID}")

          # Vérifier que c'est du JSON valide
          if ! echo "$DATA" | jq . >/dev/null 2>&1; then
            echo "Erreur : impossible de récupérer le JSON TryHackMe"
            exit 1
          fi

          USERNAME=$(echo "$DATA" | jq -r '.data.user.username')
          LEVEL=$(echo "$DATA" | jq -r '.data.user.level')
          POINTS=$(echo "$DATA" | jq -r '.data.user.points')
          AVATAR=$(echo "$DATA" | jq -r '.data.user.avatar')

          # Générer le badge Markdown cliquable
          BADGE="[![${USERNAME} - Level ${LEVEL} - ${POINTS} pts](${AVATAR})](${PROFILE_URL})"

          # Remplacer dans README
          if grep -q "<!-- tryhackme-badge -->" "$README_FILE"; then
            sed -i "s|<!-- tryhackme-badge -->|$BADGE|g" "$README_FILE"
          else
            echo -e "\n$BADGE" >> "$README_FILE"
          fi

          # Commit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$README_FILE"
          git commit -m "Update TryHackMe badge" || echo "No changes to commit"
          git push
